version: "3"
services:
    bot:
        build: .
        depends_on: 
            - mongo
        environment: 
            - DATABASE_URI=mongodb://mongo:27017/data
        volumes: 
            - .:/plexi
    mongo:
        image: mongo