blank_issues_enabled: false
contact_links:
  - name: Discord server
    url: https://nigecat.github.io/Plexi/support
    about: Have questions or need support? Please go to the Discord server, as issues that are just support-related will be closed and redirected there.