# This workflow will do a clean install of node dependencies and build the source code
#       it will also run the linter

name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./src
      CI: true

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        working-directory: ${{ env.working-directory }}
        run: npm install
          
      - name: Run lint
        working-directory: ${{ env.working-directory }}
        run: npm run lint