name: Build Docs

on:
    pull_request:
        branches:
            - master

jobs:
    build:
        name: Build
        timeout-minutes: 5
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Install bundler
              run: sudo apt install ruby-bundler

            - name: Install dependencies
              run: bundle install

            - name: Run build
              run: |
                cd docs
                bundle exec jekyll build --verbose