name: Build Docs

on:
    pull_request:
        branches:
            - master

jobs:
    build:
        name: Build
        timeout-minutes: 5
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: docs
        steps:
            - uses: actions/checkout@v2

            - name: Cache dependencies
              uses: actions/cache@v2
              with:
                path: vendor/bundle
                key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
                restore-keys: ${{ runner.os }}-gems-

            - name: Install bundler
              run: sudo apt install ruby-bundler

            - name: Install dependencies
              run: |
                bundle config path vendor/bundle
                bundle install --jobs 4 --retry 3

            - name: Run build
              run: bundle exec jekyll build --verbose