# This workflow will do a clean install of node dependencies and build the source code

name: Node.js CI

on:
  push:
    branches: [ rewrite ]
  pull_request:
    branches: [ rewrite ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      working-directory: ./src

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        working-directory: ${{ env.working-directory }}
        continue-on-error: true
        run: | 
          npm ci &> /dev/null || true
          
      - name: Run test
        working-directory: ${{ env.working-directory }}
        run: |
          npm run test

      - name: Run lint
        working-directory: ${{ env.working-directory }}
        run: |
          npm run lint